create table regions (
	    REGIONS_ID INT NOT NULL PRIMARY KEY,
	    REGIONS_NAME VARCHAR(25)
	);
	create table countries (
	    COUNTRY_ID VARCHAR(2) NOT NULL PRIMARY KEY,
	    COUNTRY_NAME VARCHAR(40),
	    REGIONS_ID INT REFERENCES regions(REGIONS_ID)
	);
	create table locations (
	    LOCATIONS_ID INT NOT NULL PRIMARY KEY,
	    STREET_ADDRESS VARCHAR(25),
	    POSTAL_CODE VARCHAR(25),
	    CITY VARCHAR(12),
	    STATE_PROVINCE VARCHAR(12),
	    COUNTRY_ID VARCHAR(2) REFERENCES countries(COUNTRY_ID)
	);
	create table departments (
	    DEPARTMENTS_ID INT NOT NULL PRIMARY KEY,
	    DEPARTMENTS_NAME VARCHAR(20),
	    MANAGER_ID INT,
	    LOCATIONS_ID INT REFERENCES locations(LOCATIONS_ID)
	);
	create table jobs (
	    JOB_ID VARCHAR(10) NOT NULL PRIMARY KEY,
	    JOB_TITLE VARCHAR(35),
	    MIN_SALARY INT,
	    MAX_SALARY INT
	);
	create table job_history (
	    EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
	    START_DATE DATE NOT NULL ,
	    END_DATE DATE,
	    JOB_ID VARCHAR(10) REFERENCES jobs(JOB_ID),
	    DEPARTMENTS_ID INT
	);
	create table employees(
	    EMPLOYEE_ID INT REFERENCES job_history(EMPLOYEE_ID),
	    FIRST_NAME VARCHAR[20],
	    LAST_NAME VARCHAR[25],
	    EMAIL VARCHAR[25],
	    PHONE_NUMBER VARCHAR[20],
	    HIRE_DATE DATE,
	    JOB_ID VARCHAR(10),
	    SALARY INT,
	    COMMISSION_PCT INT,
	    MANAGER_ID INT,
	    DEPARTMENTS_ID INT REFERENCES departments(DEPARTMENTS_ID)
	);
	create table jobs_grades(
	    GRADE_LEVEL VARCHAR(2) NOT NULL PRIMARY KEY,
	    LOWEST_SAL INT,
	    HIGHEST_SAL INT
	);